/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "zsjxfkttlvkjxjkhvqjc"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpzanhma3R0bHZranhqa2h2cWpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NTU3NDAsImV4cCI6MjA3MTQzMTc0MH0.A-rWvzDgkZf3WDBDe_4QuoqjZeV5v-CzI3L9Kim_2Fc"